export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER_FAIL = 'RECEIVE_USER_FAIL';
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER_SUCCESS';
//
export const REQUEST_REGISTER_USER = 'REQUEST_REGISTER_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
//
export const LOG_USER_OUT = 'LOG_USER_OUT';
